<div align="center">
<font face="Arial" size="3" color="#800040">

<b>
<a href="index.html">Home</a> |
<a href="charter.html">Charter</a> |
<a href="tisane.html">Tisane</a> |
<a href="mailto:ek-herbs-subscribe@eastkingdom.org">Guild Mailing List</a> | <a href="http://www.yahoogroups.com/subscribe/SCA-Herbalist" target="new">Yahoo Mailing List</a><br>
Gallery |
Events-Meetings-Classes |
<a href="classnotes.html">Classrooms</a> |
<a href="disclaimer.html"> Disclaimer</a><br>
</b>
</p>
</div>

<br />
<center><i><?include "modified.inc";?></i></center>
